apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bksyk3taa-nodejs 
  janus-idp.io/tekton: bksyk3taa-nodejs
  backstage.io/kubernetes-id: bksyk3taa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bksyk3taa-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  