apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bksyk3taa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bksyk3taa-nodejs 
  name: bksyk3taa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bksyk3taa-nodejs 
